---
- name: install the package
  ansible.builtin.yum:
    name: "{{ web_server }}"
    state: present
- name: Template the httpd.j2
  ansible.builtin.template:
    src: templates/httpd.j2
    dest: "{{ web_config_file }}"
  notify: restart_httpd
- name: Open firewalld ports
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

