---
- name: Managing Software Packages
  hosts: ansible1
  vars:
    my_package: virt-manager
  tasks:
  - name: install the package
    yum:
      name: "{{ my_package }}"
      state: present
  - name: update the packge facts
    package_facts:
      manager: auto
  - name: show the facts for package
    debug:
      var: ansible_facts.packages[my_package]
    when: my_package in ansible_facts.packages
  - name: connect to example repo
    yum_repository:
      name: example repo
      description: RHCE example repo
      file: examplerepo
      baseurl: ftp://ftp.redhat.com/pub/redhat/linux/enterprise/$releasever/en/os/SRPMS/
      gpgcheck: no
