---
- name: install and start the vsftpd service
  hosts: all
  tasks: 
  - name: install vsftpd
    yum:
      name: vsftpd
      state: latest
  - name: start and enable sftpd service
    service:
      name: vsftpd
      state: started
      enabled: yes
