---
- name: installing a template file
  hosts: ansible1
  tasks:
    - name: install http
      yum:
        name: httpd
        state: latest
    - name: start and enable service
      service:
        name: httpd
        enabled: yes
        state: started
    - name: install vhost config file
      template:
        src: listing813.j2
        dest: /etc/httpd/conf.d/vhost.conf
        owner: root
        group: root
        mode: 0644
    - name: restart httpd
      service: 
        name: httpd
        state: restarted

