---
- name: Create user with encrypted password
  hosts: ansible2
  vars_prompt:
  - name: passw
    prompt: which password do you want to use
  vars:
    user: aron
  tasks:
  - debug:
      msg: "{{ '{{ passw }}'| password_hash('sha512','myrandomsalt') }}"
    register: mypass
  - debug:
      var: mypass
  - name: create a user
    user:
      name: "{{ user }}"
      password: "{{ mypass.msg}}"
