---
- name: install, configure, start and enable ftp
  hosts: ansible1
  tasks:
  - name: install ftp server
    yum:
      name: vsftpd
      state: present
  - name:
    lineinfile:
      path: /etc/vsftpd/vsftpd.conf
      regexp: '^anonymous_enable=NO'
      line: 'anonymous_enable=YES'
  - name: start FTP server
    service:
      name: vsftpd
      state: started
      enabled: yes
  - name: open firewall for FTP
    firewalld:
      service: ftp
      state: enabled
      permanent: yes
      immediate: yes

- name: setup the repo
  hosts: ansible1
  tasks:
  - name: make dir
    file:
      path: /var/ftp/repo
      state: directory
  - name: download packages
    yum:
      download_only: yes
      download_dir: /var/ftp/repo
  - name: install createrepo_c
    yum:
      name: createrepo_c
      state: latest
  - name: createrepo
    command: createrepo_c /var/ftp/repo
    notify:
    - restart_ftp
  handlers:
  - name: restart_ftp
    service:
      name: vsftpd
      state: restarted
       
