---
- name: install packages on host ansible2
  hosts: ansible2
  vars_files: vars/packages
  tasks:
  - name: install packages
    yum:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop: "{{ packages }}"
    when: ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution_major_version'] == "8"
  - name: debug
    debug:
      msg: "Host '{{ ansible_facts['hostname'] }}' does not meet minimal requirements"

- name: create a file on localhost
  hosts: localhost
  tasks:
  - name: create a file /tmp/index.html
    copy:
      content: "welcome to my webserver"
      dest: /tmp/index.html
- name: copy to file to webserver host
  vars_files: vars/packages
  hosts: ansible2
  tasks:
  - name: copy file to managed node
    copy: 
      src: /tmp/index.html
      dest: /var/www/html
    notify: restart_web
  - name: permit traffic in default zone for https service
    ansible.posix.firewalld:
      service: "{{ item.name }}"
      permanent: yes
      state: "{{ item.state }}"
    loop: "{{ firewall }}"
  handlers:
  - name: restart_web
    service:
      name: httpd
      state: restarted
      
