---
- name: setup a service
  hosts: ansible2
  tasks:
  - name: include the service task file
    include_tasks: tasks/service.yml
    vars:
      package: httpd
      service: httpd
    when: ansible_facts['os_family'] == 'RedHat'
  - name: import the firewall file
    import_tasks: tasks/firewall.yml
    vars:
      firewall_package: firewalld
      firewall_service: firewalld
      firewall_rules:
      - http
      - https

- name: install vsftpd on ansible2 
  vars_files: exercise103-vars.yml
  hosts: ansible2
  tasks:
  - name: install and enable vsftpd
    import_tasks: exercise103-ftp.yml
  - name: copy the README file
    import_tasks: exercise103-copy.yml
