# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  
  config.ssh.insert_key = false
  
  config.vm.synced_folder ".", "/vagrant", disabled: true 

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.linked_clone = true
  end
  
  # App server 1
  config.vm.define "control" do |app|
    app.vm.hostname = "control.example.com"
    app.vm.network :private_network, ip: "192.168.60.4"
  end

  # App server 2
  config.vm.define "ansible1" do |app|
    app.vm.hostname = "ansible1.example.com"
    app.vm.network :private_network, ip: "192.168.60.5"
  end

  # App server 3
  config.vm.define "ansible2" do |app|
    app.vm.hostname = "ansible2.example.com"
    app.vm.network :private_network, ip: "192.168.60.6"
  end

end
