# SPDX-License-Identifier: BSD-3-Clause
---
- name: Manage autoconnect
  hosts: ansible2
  vars:
    network_connections:
    - name: enp0s3
      type: ethernet
      ip:
        route_metric4: 100
        dhcp4: false
        address:
          - fc00::202/64

  roles:
    - rhel-system-roles.network
