---
- name: copy the fact
  hosts: ansible1
  vars:
    facts_dir: /etc/ansible/facts.d
  tasks:
  - name: create ansible fact dir
    file:
      name: "{{ facts_dir }}"
      state: directory
  - name: copy localfact file
    copy:
      content: |
        [facts]
        type=production
      dest: "{{ facts_dir }}/local.fact"
  - name: gather facts again
    gather_facts:
  - name: debug fact
    debug:
      var: ansible_facts.ansible_local.local.facts.type
