---
roles:
  - src: geerlingguy.docker
  - src: geerlingguy.nginx


collections:
  - name: "/home/ansible/ansible-posix-1.5.4.tar.gz"
    type: file
  
  - name: "/home/ansible/community-general-8.3.0.tar.gz"
    type: file

