---
- name: Ensure that lvm is configured
  hosts: all
  ignore_errors: yes
  tasks:
  - name: check if second disk exists
    assert:
      that:
        - ansible_facts['devices']['sdb'] is defined
      fail_msg: "no work to do"
  - name: Ensure that disk are formatted
    parted:
      device: /dev/sdb
      number: 1
      state: present
      part_end: "100%"
      flags: [ lvm ]
  - name: Ensure that volume group is created
    community.general.lvg:
      vg: vgfiles
      pvs: /dev/sdb1
  - name: Create a logical volume of 512m
    community.general.lvol:
      vg: vgfiles
      lv: lvfiles
      size: 1g
  - name: create a directory
    file:
      path: /lvfiles
      state: directory
  - name: gather facts
    ansible.builtin.gather_facts:
  - name: Create a ext4 filesystem on /dev/sdb1
    community.general.filesystem:
      fstype: xfs
      dev: /dev/vgfiles/lvfiles
  - name: Mount up the logical volume
    ansible.posix.mount:
      path: /lvfiles
      src: /dev/vgfiles/lvfiles
      fstype: xfs
      state: mounted


