---
- name: Ensure that web server is configured
  hosts: webservers
  tasks:
  - name: install the package
    ansible.builtin.yum:
      name: "{{ web_server }}"
      state: present
  - name: Template the httpd.j2
    ansible.builtin.template:
      src: templates/httpd.j2
      dest: "{{ web_config_file }}"
    notify: restart_httpd
  handlers:
  - name: restart_httpd
    service:
      name: httpd
      state: restarted
