---
- name: Ensure web server is Unistalled
  hosts: ansible2
  tasks:
  - name: remove the welcome text
    file:
      path: "/var/www/html/index.html"
      state: absent
  - name: Uninstall packages
    yum:
      name: httpd
      state: absent
  - name: stop httpd service
    service:
      name: httpd
      state: stopped
      enabled: false

