---
- hosts: all
  become: true

  vars_files:
  - vars.yml
  
  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.yum:
        update_cache: true

  handlers:
    - name: restart solr
      service: name=solr state=restarted

  tasks:
    - name: Install Java.
      ansible.builtin.yum: name=java-11-openjdk-devel state=present
  
    - name: Download solr
      get_url:
        url: "https://www.apache.org/dyn/closer.lua/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz?action=download"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        # checksum: "{{ solr_checksum  }}"

    - name: Download solr
      ansible.builtin.unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README"

    - name: Install Solr.
      ansible.builtin.command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /var
        -u solr
        -s solr 
        -p 9090
        creates={{ solr_dir }}/bin/solr

    - name: Ensure solr is started and enabled at boot
      service: name=solr state=started enabled=yes
