---
- name: set up hosts that have and sdb device
  hosts: all
  tasks:
  - name:
    yum:
      name: 'lvm*'
      state: present
  - name: getting out with nice failure message if there is no second disk
    fail:
      msg: there is no second disk
    when: ansible_facts['devices']['sdb'] is not defined
  - name: create the partition
    parted:
      device: /dev/sdb
      number: 1
      state: present
  - name: create vol group
    lvg:
      pvs: /dev/sdb1
      vg: vgfiles
  - name: run the setup module so that we can use updated facts
    setup:
  - name: get the vg size and store it in a variable
    set_fact:
      vgsize: "{{ ansible_facts['lvm']['vgs']['vgfiles']['size_g'] | int }}"
  - name: show vgsize value
    debug:
      var: "{{ vgsize }}"
  - name: create an LVM on big volume groups
    lvol:
      vg: vgfiles
      lv: lvfiles
      size: 6g
    when: vgsize | int > 5
  - name: create an LVM on small volume groups
    lvol:
      vg: vgfiles
      lv: lvfiles
      size: 3g
    when: vgsize | int <= 5
  - name: formatting the xfs fs
    filesystem:
      dev: /dev/vgfiles/lvfiles
      fstype: xfs
  - name: mounting /dev/vgfiles/lvfiles
    mount:
      path: /file
      state: mounted
      src: /dev/vgfiles/lvfiles
      fstype: xfs

