---
- name: copy multiline text
  hosts: ansible1
  tasks:
  - name: copy text
    copy:
      content: |
        line 1
        line 2
      dest: /tmp/multiline.txt

  - name: copy more text
    copy:
      content: >
        line 1 
        line 2
      dest: /tmp/multiline1.txt
