---
- name: prepare localhost
  hosts: localhost
  tasks:
  - name: create the local user, including ssh key
    user:
      name: "{{ username }}"
      generate_ssh_key: true
      ssh_key_comment: "{{ username }}@{{ ansible_fqdn }}"
  - name: create a dir to store the file
    file:
      name: "{{ username }}"
      state: directory
  - name: copy the local user ssh key to temporary {{ username }} key
    shell: 'cat /home/{{ username }}/.ssh/id_rsa.pub > {{ username }}/id_rsa.pub'
  - name: verify that file exists
    command: ls -l {{ username }}/

- name: setup the remote host
  hosts: ansible2
  tasks:
  - name: create remote user, no need for SSH key
    user:
      name: "{{ username }}"
  - name: use authorized_key to set the password
    authorized_key:
      user: "{{ username }}"
      key: "{{ lookup('file', './'+ username +'/id_rsa.pub') }}"

