---
- name: install vsftpd
  hosts: all
  serial: 2
  tasks:
  - name: install vsftpd
    vars:
      package: vsftpd
      service: vsftpd
    import_tasks: tasks/service.yml
  - name: open port in firewall
    vars:
      firewall_package: firewalld
      firewall_service: firewalld
      firewall_rules:
      - ftp
    import_tasks: tasks/firewall.yml

- name: configure VSFTPD using a template
  hosts: all
  serial: 2
  tasks:
  - name: import conf task
    vars:
      anonymous_enable: yes
      local_enable: yes
      write_enable: yes
      anon_upload_enable: yes
    import_tasks: tasks/copy-ftp-conf.yml

- name: configure vsftpd permissions and selinux
  hosts: all
  serial: 2
  tasks:
  - name: import selinux tasks
    vars:
      file_path: /var/ftp/pub
      file_mode: '0777'
      boolean_name: ftpd_anon_write
      context_type: public_content_rw_t
    import_tasks: tasks/selinux.yml
  handlers:
  - name: run restorecon
    command: restorecon -vR "{{ file_path }}"
